-- AWS_INSTANCES: INSTANCE_ID, INSTANCE_NAME, REGION_ID, CPU_UTILIZATION
-- GCP_INSTANCES: INSTANCE_ID, INSTANCE_NAME, REGION_ID, MEMORY_UTILIZATION
-- REGION : REGION_ID, REGION_NAME
/*
INSTANCE_NAME, PROVIDER, REGION_NAME, STATUS 최종 출력
- PROVIDER는 AWS 면 'AWS', GCP 면 'GCP'를 출력
- STATUS는 시스템별로 다른 기준을 적용하여 '경고' 또는 '정상'으로 출력
AWS: CPU_UTILIZATION이 90 이상이면 '경고', 미만이면 '정상'
GCP: MEMORY_UTILIZATION이 80 이상이면 '경고', 미만이면 '정상'
-STATUS가 '경고'인 데이터가 먼저 나오도록 정렬하고, 상태가 같다면 REGION_NAME 오름차순, 그다음 INSTANCE_NAME 오름차순으로 정렬합니다.
*/

SELECT T.INSTANCE_NAME, T.PROVIDER, T.REGION_NAME, T.STATUS
FROM (
    SELECT A.INSTANCE_NAME, 'AWS' AS PROVIDER, R.REGION_NAME, 
    CASE 
        WHEN A.CPU_UTILIZATION>=90 THEN '경고'
        ELSE '정상'
    END AS STATUS
    FROM AWS_INSTANCES A
    JOIN REGION R ON A.REGION_ID=R.REGION_ID
    
    UNION ALL

    SELECT G.INSTANCE_NAME, 'GCP' AS PROVIDER, R.REGION_NAME, 
    CASE 
        WHEN G.MEMORY_UTILIZATION>=80 THEN '경고'
        ELSE '정상'
    END AS STATUS
    FROM GCP_INSTANCES G
    JOIN REGION R ON G.REGION_ID=R.REGION_ID
) AS T

ORDER BY T.STATUS, T.REGION_NAME, T.INSTANCE_NAME